extends Resource

@export var weapon_list = [
	{
		"name" : "Blade",
		"scene_name" : "blade",
		"damage" : 0.1,
		"rate_of_fire" : 4,
		"speed" : 10,
		"energy_cost" : 5,
		"range" : 5.0,
		"level_required" : 1,
		"enabled" : false,
		"stays_active" : true,
		"active" : false,
		"gravity" : false,
		"target_lock" : false,
		"model" : "blade",
	}, {
		"name" : "Laser Pistol",
		"scene_name" : "laser_pistol",
		"damage" : 2,
		"rate_of_fire" : 3,
		"speed" : 50,
		"energy_cost" : 1,
		"range" : 100.0,
		"level_required" : 1,
		"enabled" : true,
		"stays_active" : false,
		"active" : false,
		"gravity" : false,
		"target_lock" : false,
		"model" : null,
	}, {
		"name" : "Laser Rifle",
		"scene_name" : "laser_rifle",
		"damage" : 5,
		"rate_of_fire" : 5,
		"speed" : 50,
		"energy_cost" : 5,
		"range" : 100.0,
		"level_required" : 5,
		"enabled" : false,
		"stays_active" : false,
		"active" : false,
		"gravity" : false,
		"target_lock" : false,
		"model" : null,
	}, {
		"name" : "Laser Blaster",
		"scene_name" : "laser_blaster",
		"damage" : 4,
		"rate_of_fire" : 5,
		"speed" : 50,
		"energy_cost" : 4,
		"range" : 100.0,
		"level_required" : 7,
		"enabled" : false,
		"stays_active" : false,
		"active" : false,
		"gravity" : false,
		"target_lock" : false,
		"model" : null,
	}, {
		"name" : "Laser Repeater",
		"scene_name" : "laser_repeater",
		"damage" : 1,
		"rate_of_fire" : 10,
		"speed" : 50,
		"energy_cost" : 1,
		"range" : 100.0,
		"level_required" : 9,
		"enabled" : false,
		"stays_active" : false,
		"active" : false,
		"gravity" : false,
		"target_lock" : false,
		"model" : "blaster",
	}, {
		"name" : "Plasma Blaster",
		"scene_name" : "plasma_blaster",
		"damage" : 10,
		"rate_of_fire" : 5,
		"speed" : 40,
		"energy_cost" : 15,
		"range" : 100.0,
		"level_required" : 10,
		"enabled" : false,
		"stays_active" : false,
		"active" : false,
		"gravity" : true,
		"target_lock" : false,
		"model" : "blaster",
	}, {
		"name" : "Plasma Cannon",
		"scene_name" : "plasma_cannon",
		"damage" : 20,
		"rate_of_fire" : 5,
		"speed" : 40,
		"energy_cost" : 25,
		"range" : 100.0,
		"level_required" : 15,
		"enabled" : false,
		"stays_active" : false,
		"active" : false,
		"gravity" : true,
		"target_lock" : false,
		"model" : "zooka",
	}, {
		"name" : "Rail Gun",
		"scene_name" : "rail_gun",
		"damage" : 20,
		"rate_of_fire" : 5,
		"speed" : 50,
		"energy_cost" : 15,
		"range" : 100.0,
		"level_required" : 15,
		"enabled" : false,
		"stays_active" : false,
		"active" : false,
		"gravity" : false,
		"target_lock" : false,
		"model" : "blaster",
	}, {
		"name" : "Missile",
		"scene_name" : "missile",
		"damage" : 20,
		"rate_of_fire" : 5,
		"speed" : 40,
		"energy_cost" : 10,
		"range" : 100.0,
		"level_required" : 20,
		"enabled" : false,
		"stays_active" : false,
		"active" : false,
		"gravity" : false,
		"target_lock" : false,
		"model" : "zooka",
	}, {
		"name" : "Homing Missile",
		"scene_name" : "missile",
		"damage" : 20,
		"rate_of_fire" : 5,
		"speed" : 40,
		"energy_cost" : 10,
		"range" : 100.0,
		"level_required" : 25,
		"enabled" : false,
		"stays_active" : false,
		"active" : false,
		"gravity" : false,
		"target_lock" : true,
		"model" : "zooka",
	}, {
		"name" : " Jolt",
		"scene_name" : "jolt",
		"damage" : 10,
		"rate_of_fire" : 5,
		"speed" : 15,
		"energy_cost" : 10,
		"range" : 5.0,
		"level_required" : 50,
		"enabled" : false,
		"stays_active" : false,
		"active" : false,
		"gravity" : false,
		"target_lock" : false,
		"model" : null,
	}, 
]

func get_weapon_properties( weapon_index : int ) :
	return weapon_list[ weapon_index ]

func get_weapon_property( weapon_index : int, property : String ) :
	return weapon_list[ weapon_index ][ property ]

func set_weapon_active( weapon_index : int ) :
	if weapon_list[ weapon_index ][ "active" ] :
		weapon_list[ weapon_index ][ "active" ] = false
	else :
		weapon_list[ weapon_index ][ "active" ] = true

func get_weapon_count( ) :
	return weapon_list.size( )
